[build]
  publish = "public"

[dev]
  framework = "#custom"
  command = "npx hugo server --disableFastRender"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[build.environment]
  NODE_VERSION = "22"

[context.production]
  command = "npm run check && npx hugo --gc --minify -b $URL"

[context.deploy-preview]
  command = "npm run check && npx hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run check && npx hugo --gc --minify -b $DEPLOY_PRIME_URL"
